#!/usr/bin/env sh
set -Eeuo pipefail;

echo 'Installing layers and system packages for toolbox:';
curl -fsSL https://raw.githubusercontent.com/git-rafael/toolbox/master/layers/ops/bin/packagectl \
| LAYERS='ops ops-data ops-systems dev dev-data dev-security dev-systems' sh;
